apiVersion: apps/v1
kind: Deployment
metadata:
  name: alluvial-task
  labels:
    app: alluvial-task
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alluvial-task
  template:
    metadata:
      labels:
        app: alluvial-task
    spec:
      containers:
        - name: alluvial-task
          image: <DOCKER_HUB_USERNAME>/alluvial-task:latest}
          ports:
            - containerPort: 8080
            - containerPort: 8081
              name: health-port
          env:
            - name: ETH_CLIENTS
              value: "https://eth-mainnet.g.alchemy.com/v2/SYpDdGSITBpoS7VC6Duq02FmvWmbaS2i,https://mainnet.infura.io/v3/03165944e0a24e349d21b977cad5e8a2,https://virtual.mainnet.rpc.tenderly.co/b6046e1c-b375-407f-a681-0048d52f6630"
            - name: SERVER_ADDRESS
              value: ":8080"
            - name: HEALTH_CHECK_ADDRESS
              value: ":8081"
          livenessProbe:
            httpGet:
              path: /live
              port: health-port
            initialDelaySeconds: 0
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 18
          readinessProbe:
            httpGet:
              path: /ready
              port: health-port
            initialDelaySeconds: 0
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 18