apiVersion: v1
kind: Service
metadata:
  name: alluvial-task
spec:
  selector:
    app: alluvial-task
  ports:
    - name: app
      protocol: TCP
      port: 80
      targetPort: 8080
    - name: health
      protocol: TCP
      port: 81
      targetPort: 8081